---
version: "3"
 
networks:
 tig:

services:
 influxdb:
   container_name: influxdb
   expose:
     - 8086
     - 8083
   networks:
     - tig
   image: influxdb:1.8.0
 
 telegraf:
   container_name: telegraf
   image: telegraf:1.14.3
   networks:
     - tig
   volumes:
     - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
   depends_on:
     - influxdb
 
 grafana:
   container_name: grafana
   environment:
     GF_SECURITY_ADMIN_USER: arista
     GF_SECURITY_ADMIN_PASSWORD: arista
   ports:
     - '3000:3000'
   networks:
     - tig
   image: grafana/grafana:7.0.3
   volumes:
      - $PWD/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
   depends_on:
     - influxdb

 